# Parte 1: Numpy

In [2]:
import numpy as np

#### 1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [12]:
bool_array = np.ones(1000,dtype='bool')
size_bytes = bool_array.nbytes
print(f"El tamaño de un array de 1000 elementos tipo bool es: {size_bytes} bytes")

El tamaño de un array de 1000 elementos tipo bool es: 1000 bytes


#### 2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [28]:
enteros_pares = np.arange(2,101,2)
enteros_pares_dec = enteros_pares[::-1]
print(f"{enteros_pares_dec[-10:] = :}")

enteros_pares_dec[-10:] = [20 18 16 14 12 10  8  6  4  2]


#### 3. Dado el array

$\begin{bmatrix}
2 & 4 & 5 & 6 \\
0 & 3 & 7 & 4\\
8 & 8 & 5 & 2\\
1 & 5 & 6 & 1
\end{bmatrix}$

**Seleccione con una instrucción el subarray de elementos**

$\begin{bmatrix}
0 & 3 & 4 & 7 
\end{bmatrix}$

In [31]:
ex3_array = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])
ex3_1_array = ex3_array[1]
ex3_1_array

array([0, 3, 7, 4])

**Después, seleccione el subarray de elementos**

$\begin{bmatrix}
2 & 5\\ 
8 & 5 
\end{bmatrix}$

In [42]:
ex3_2_array = ex3_array[::2,::2]
ex3_2_array

array([[2, 5],
       [8, 5]])

#### 4. Dados los arrays 
$a = [1, 4, 2, 7]$

$b = [1, 3, 2, 9]$

**obtenga la media aritmética de la diferencia (a-b)**

In [48]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])
print(f"{a = :}\n{b = :}\n{(a-b) = :}\n{(a-b).mean() = :}")

a = [1 4 2 7]
b = [1 3 2 9]
(a-b) = [ 0  1  0 -2]
(a-b).mean() = -0.25


####  5. Tengo valores de cordenadas (x, y) en las columnas del array
$\begin{bmatrix}
1.33 & 4.5\\
30.0 & 10.7\\
70.2 & 0.5
\end{bmatrix}$

In [49]:
ex5_array = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])
ex5_array

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ]])

**Agregue a este array las coordenadas (37.1, -3.6).**

In [54]:
ex5_array_add = np.append(ex5_array,[[37.1,-3.6]],axis=0)
ex5_array_add

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

**Muestre en pantalla las dimensiones del nuevo array.**

In [60]:
dim = ex5_array_add.shape
print(f"El array tiene {dim[0]} filas y {dim[1]} columnas.")

El array tiene 4 filas y 2 columnas.


#### 6. Copie el array del ejercicio anterior. Traspóngalo.).

In [102]:
ex6_array = ex5_array_add.copy()
ex6_array

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

In [103]:
ex6_array_trans = ex6_array.T
ex6_array_trans

array([[ 1.33, 30.  , 70.2 , 37.1 ],
       [ 4.5 , 10.7 ,  0.5 , -3.6 ]])

**Agregue ahora dos nuevos pares de coordenadas: 
(10.8, 3.0) y (35.8, 12.0).**

In [106]:
np.concatenate((ex6_array_trans,np.array([[10.8,3.0],[35.8,12.0]]).T),axis=1)

array([[ 1.33, 30.  , 70.2 , 37.1 , 10.8 , 35.8 ],
       [ 4.5 , 10.7 ,  0.5 , -3.6 ,  3.  , 12.  ]])

# Parte 2: Exploración y Minería de Datos

In [107]:
import pandas as pd
import matplotlib.pyplot as plt